#!/bin/sh
cat 1>&2 <<EOF
This system uses rpm-ostree, not $0.
For more information, see:
https://github.com/projectatomic/rpm-ostree
https://fedoraproject.org/wiki/Changes/WorkstationOstree
EOF
exit 1
